# This file contains map of relationships between
# external networks on source and destination clouds.
#
# Use the following format:
# <old external network id>: <new external network id>
#
# F.e.:
# cfd33270-8a4c-4fb9-8af9-7c83f82b8a5b: 7c325f53-b12b-4b07-b78a-0478d863f625